----数据质量监控规则表
drop table if exists ODS_DATA_CHECK_RULE;
create table ODS_DATA_CHECK_RULE(
	CHECK_RULE_ID STRING COMMENT '核查规则编码',
	CHECK_RULE_NAME STRING COMMENT '核查规则名称',
	CHECK_RULE_DESC STRING COMMENT '核查规则内容描述',
	CHECK_RULE_TYPE_ID STRING COMMENT '核查规则类型编码',
	CHECK_RULE_TYPE_NAME STRING COMMENT '核查规则类型名称',
	CHECK_RULE_STATUS STRING COMMENT '状态',
	CHECK_RULE_OWNER STRING COMMENT '负责人',
	CHECK_RULE_EMAIL STRING COMMENT '负责人邮箱',
	CHECK_RULE_PHONE STRING COMMENT '负责人手机',
	CHECK_RULE_TABLE STRING COMMENT '数据表',
	CHECK_RULE_SQL STRING COMMENT '监控脚本'
)COMMENT '数据质量监控规则表';