----订单表
drop table if exists ODS_EBUSI_ORDERS;
create table ODS_EBUSI_ORDERS(
	ORDER_ID BIGINT COMMENT '订单号',
	CUSTOMER_ID BIGINT COMMENT '客户编码',
	PRODUCT_ID BIGINT COMMENT '产品编码',
	PRODUCT_CNT BIGINT COMMENT '产品数量',
	ORDER_AMT DOUBLE COMMENT '产品费用',
	SHIPPING_TYPE_ID BIGINT COMMENT '运输类型',
	ORDER_TIME STRING COMMENT '订单时间'
)COMMENT '订单表';

----客户表
drop table if exists ODS_EBUSI_CUSTOMERS;
create table ODS_EBUSI_CUSTOMERS(
	CUSTOMER_ID BIGINT COMMENT '客户编码',
	CUSTOMER_NAME	STRING COMMENT '客户名称',
	AGE BIGINT COMMENT '年龄',
	GENDER BIGINT COMMENT '性别编码',
	CITY_ID BIGINT COMMENT '城市编码',
	CITY_NAME STRING COMMENT '城市名称',
	PROVINCE_ID BIGINT COMMENT '省份编码',
	PROVINCE_NAME STRING COMMENT '省份名称',
	GEN_DATE STRING COMMENT '出生日期'
)COMMENT '客户表';

----配送表
drop table if exists ODS_EBUSI_DISPATCH;
create table ODS_EBUSI_DISPATCH(
	DISPATCH_ID BIGINT COMMENT '配送单号',
	ORDER_ID BIGINT COMMENT '订单号',
	EXPRESS_STAFF_ID BIGINT COMMENT '配送员编码',
	STOREHOUSE_ID BIGINT COMMENT '仓库编码',
	EXPECT_TIME DATETIME COMMENT '期望到货时间',
	DISPATCH_TIME DATETIME COMMENT '开始送货时间'
)COMMENT '配送表';

----产品表
drop table if exists ODS_EBUSI_DIM_PRODUCT;
create table ODS_EBUSI_DIM_PRODUCT(
	PRODUCT_ID BIGINT COMMENT '产品编码',
	PRODUCT_NAME	STRING COMMENT '产品名称',
	PRICE DOUBLE COMMENT '产品价格',
	PRODUCT_CATEGORY_ID BIGINT COMMENT '产品类别'
)COMMENT '产品表';

----省份表
drop table if exists ODS_EBUSI_DIM_PROVINCE;
create table ODS_EBUSI_DIM_PROVINCE(
	PROVINCE_ID BIGINT COMMENT '省份编码',
	PROVINCE_NAME	STRING COMMENT '省份名称'
)COMMENT '省份表';

----城市表
drop table if exists ODS_EBUSI_DIM_CITY;
create table ODS_EBUSI_DIM_CITY(
	CITY_ID BIGINT COMMENT '城市编码',
	CITY_NAME	STRING COMMENT '城市名称',
	LNG DOUBLE  COMMENT '经度',
	LAT DOUBLE  COMMENT '维度',
	PROVINCE_ID BIGINT COMMENT '省份编码'
)COMMENT '城市表';
