----订单表
drop table if exists ODS_EBUSI_JOB_ORDERS;
create table ODS_EBUSI_JOB_ORDERS(
	ORDER_ID BIGINT COMMENT '订单号',
	CUSTOMER_ID BIGINT COMMENT '客户编码',
	PRODUCT_ID BIGINT COMMENT '产品编码',
	PRODUCT_CNT BIGINT COMMENT '产品数量',
	ORDER_AMT DOUBLE COMMENT '产品费用',
	SHIPPING_TYPE_ID BIGINT COMMENT '运输类型',
	ORDER_TIME STRING COMMENT '订单时间',
	ORDER_STATUS STRING COMMENT '订单状态'
)COMMENT '订单表';

----付款单
drop table if exists ODS_EBUSI_JOB_PAYMENTS;
create table ODS_EBUSI_JOB_PAYMENTS(
	PAYMENT_ID BIGINT COMMENT '付款单号',
	ORDER_ID BIGINT COMMENT '订单号',
	PAY_METHOD_ID BIGINT COMMENT '付款方式编码',
	PRODUCT_ID BIGINT COMMENT '产品编码',
	PAY_AMT DOUBLE COMMENT '付款金额',
	DISCOUNT_AMT DOUBLE COMMENT '减免金额',
	PAY_TIME STRING COMMENT '付款时间'
)COMMENT '付款表';

----配送表
drop table if exists ODS_EBUSI_JOB_DISPATCH;
create table ODS_EBUSI_JOB_DISPATCH(
	DISPATCH_ID BIGINT COMMENT '配送单号',
	ORDER_ID BIGINT COMMENT '订单号',
	PRODUCT_ID BIGINT COMMENT '产品编码',
	EXPRESS_STAFF_ID BIGINT COMMENT '配送员编码',
	STOREHOUSE_ID BIGINT COMMENT '仓库编码',
	EXPECT_TIME DATETIME COMMENT '期望到货时间',
	DISPATCH_TIME DATETIME COMMENT '开始送货时间'
)COMMENT '配送表';

----订单状态
drop table if exists ODS_EBUSI_JOB_DIM_ORDER_STATUS;
create table ODS_EBUSI_JOB_DIM_ORDER_STATUS(
	ORDER_STATUS STRING COMMENT '订单状态',
	ORDER_STATUS_DESC STRING COMMENT '订单状态描述'  ----1：待付款 2：已付款 3：取消
)COMMENT '订单状态';
